<a href="https://colab.research.google.com/github/yym10618/Colab/blob/master/Ch03.%EB%94%A5%EB%9F%AC%EB%8B%9D%20%EC%8B%A4%EC%8A%B5/4_%EB%94%A5%EB%9F%AC%EB%8B%9D_CNN_%EB%AA%A8%EB%8D%B8_%ED%85%8C%EC%8A%A4%ED%8A%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
"""
날짜 : 2022/05/10
이름 : 양용민
내용 : 딥러닝 CNN 모델 테스트
"""
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets.cifar10 import load_data
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import load_model
from keras.preprocessing.image import load_img, img_to_array
from PIL import Image
tf.__version__

'2.8.0'

In [7]:
#데이터 불러오기
(cifar_train_data, cifar_train_label), (cifar_test_data, cifar_test_label) = load_data()

In [8]:
#모델학습을 위한 데이터 전처리(정규화)
cifar_train_data = cifar_train_data / 255
cifar_test_data = cifar_test_data / 255

In [9]:
#데이터 라벨을 범주형(one-hot encoding)으로 변환
cifar_train_label = to_categorical(cifar_train_label)
cifar_test_label = to_categorical(cifar_test_label)
cifar_train_label[1]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [12]:
#외부 학습모델 불러오기
model = load_model('/content/drive/MyDrive/파이썬 데이터 과학 실습/file/cifar_model.h5')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 32, 32, 32)        896       
                                                                 
 conv2d_1 (Conv2D)           (None, 32, 32, 32)        9248      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 16, 16, 32)       0         
 )                                                               
                                                                 
 dropout (Dropout)           (None, 16, 16, 32)        0         
                                                                 
 conv2d_2 (Conv2D)           (None, 16, 16, 64)        18496     
                                                                 
 conv2d_3 (Conv2D)           (None, 16, 16, 64)        36928     
                                                        

In [13]:
#모델 테스트
result = model.evaluate(cifar_test_data, cifar_test_label)
result

313/313 [==============================] - 17s 54ms/step - loss: 0.6816 - acc: 0.7753


[0.6815829277038574, 0.7753000259399414]

In [14]:
###############################################################
#이미지 로드 함수 정의
def load_image(filename):
	# load the image
	img = load_img(filename, target_size=(32, 32))
	# convert to array
	img = img_to_array(img)
	# reshape into a single sample with 3 channels
	img = img.reshape(1, 32, 32, 3)
	# prepare pixel data
	img = img.astype('float32')
	img = img / 255.0
	return img

In [15]:
img = load_image('/content/drive/MyDrive/파이썬 데이터 과학 실습/file/frog.jpg')
img

array([[[[0.36862746, 0.47058824, 0.18431373],
         [0.30588236, 0.4117647 , 0.10196079],
         [0.3019608 , 0.41568628, 0.08627451],
         ...,
         [0.37254903, 0.50980395, 0.1882353 ],
         [0.31764707, 0.4627451 , 0.16078432],
         [0.25490198, 0.4       , 0.09803922]],

        [[0.3882353 , 0.49019608, 0.20392157],
         [0.39607844, 0.5019608 , 0.18431373],
         [0.3254902 , 0.4392157 , 0.11764706],
         ...,
         [0.34509805, 0.45490196, 0.16470589],
         [0.30588236, 0.42352942, 0.13333334],
         [0.29803923, 0.4117647 , 0.09803922]],

        [[0.37254903, 0.4745098 , 0.1882353 ],
         [0.37254903, 0.47843137, 0.16078432],
         [0.31764707, 0.43137255, 0.11764706],
         ...,
         [0.3254902 , 0.40392157, 0.16470589],
         [0.3254902 , 0.4       , 0.14117648],
         [0.3372549 , 0.4117647 , 0.09411765]],

        ...,

        [[0.34509805, 0.42352942, 0.14509805],
         [0.36862746, 0.41960785, 0.2       ]

In [16]:
#이미지 모델 테스트
result = model.predict(img)
result.round()

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)