<a href="https://colab.research.google.com/github/yym10618/Colab/blob/master/Ch01.%ED%8C%8C%EC%9D%B4%EC%8D%AC%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EB%B6%84%EC%84%9D%20%EA%B8%B0%EC%B4%88/2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
날짜 : 2022/04/25
이름 : 양용민
내용 : 파이썬 Numpy 패키지 실습

Numpy 라이브러리
 - 고성능 수치계산을 위한 파이썬 라이브러리
 - 파이썬 기본 리스트보다 더 크고 빠른 연산을 위한 리스트를 제공
 - 행렬이나 대규모 다차원 배열 처리를 지원
"""
import numpy as np

In [ ]:
# 벡터(Numpy 자료구조)
v1 = np.array([1, 2, 3, 4, 5])
print(v1)

v2 = np.arange(10)
print(v2)

v3 = np.arange(100)
print(v3)

[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
# 0 ~ 1 사이의 임의의 실수 100개
rand1 = np.random.rand(100)
rand1

array([0.63765492, 0.5527305 , 0.13146429, 0.13366251, 0.13450662,
       0.79305745, 0.23793408, 0.80100743, 0.77726491, 0.20489429,
       0.59979713, 0.29553232, 0.80462704, 0.45576045, 0.69036301,
       0.24588976, 0.60873773, 0.74797508, 0.08174979, 0.75790924,
       0.33484528, 0.7737737 , 0.00303936, 0.77281012, 0.54488078,
       0.84637768, 0.83181778, 0.42872943, 0.02639648, 0.146536  ,
       0.50123281, 0.53821513, 0.63861948, 0.89123271, 0.02212627,
       0.44186828, 0.25293041, 0.2636994 , 0.87382251, 0.38428601,
       0.62619625, 0.14629662, 0.45987   , 0.51490842, 0.36529331,
       0.75160579, 0.0648671 , 0.55702887, 0.34007728, 0.60049509,
       0.81576457, 0.45285939, 0.48629116, 0.4737531 , 0.07233491,
       0.59712258, 0.47010909, 0.32297332, 0.72585098, 0.99013221,
       0.64438389, 0.73269893, 0.60907785, 0.83097424, 0.00144892,
       0.36163991, 0.69895236, 0.4546634 , 0.68565275, 0.01401938,
       0.72711712, 0.55009373, 0.66300237, 0.91500534, 0.63909

In [ ]:
# 표준 정규분포를 따르는 실수 100개
rand2 = np.random.randn(100)
rand2

array([-1.48240255,  1.5942682 ,  1.49721517,  0.44706912, -1.15254162,
        0.57783683, -1.03289352,  0.58122372, -0.53685299, -0.19143709,
       -0.88954713,  1.01129919, -0.3019905 , -0.75495741,  0.51639401,
       -1.74868838, -1.90497777,  0.0920276 , -0.38559537, -0.21251509,
        0.21289845, -0.8437064 ,  0.66488377,  0.18816047,  0.69465984,
       -1.96809172, -0.32557826,  0.41201335,  1.06596897,  2.11246727,
       -1.64602013,  0.61907264,  1.59331556,  0.96963443, -0.32342048,
        2.39222172, -0.01408236,  2.03345111, -1.94017139, -0.88948263,
       -0.0823224 , -0.56863233,  1.30971237, -2.17268273,  0.14782434,
       -0.49833961,  0.91830532,  0.87839213, -0.95671734, -0.17226352,
       -0.67859889, -0.03585363, -2.20664708,  1.30116303, -0.90449406,
        0.55740516, -1.67842529,  1.58399088,  0.48216419, -0.03974701,
        0.58256733, -0.24786027, -0.21022645, -1.41794654, -1.41547783,
        0.16284295,  1.35544564, -0.86224309,  1.71841268, -1.37

In [ ]:
# 행렬(Numpy 자료구조)
m1 = np.array([[1, 2], [3, 4]])
print(m1)

m2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m2)

m3 = np.zeros([2, 3])
print(m3)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 단위행렬
e1 = np.identity(2)
print(e1)

e2 = np.identity(3)
print(e2)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 역행렬
im1 = np.linalg.inv(m1)
print(im1)

result = m1.dot(im1)
print(result.round())

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 0.]
 [0. 1.]]


In [ ]:
# 행렬 인덱싱
mat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(mat)

print('r1 :',mat[0, 0])
print('r2 :',mat[0, :])
print('r3 :',mat[:, 0])

print('r4 :',mat[0:2, 0:2])
print('r5 :',mat[:, 0:2])
print('r6 :',mat[:, 2:4])
print('r7 :',mat[1:3, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
r1 : 1
r2 : [1 2 3 4]
r3 : [1 5 9]
r4 : [[1 2]
 [5 6]]
r5 : [[ 1  2]
 [ 5  6]
 [ 9 10]]
r6 : [[ 3  4]
 [ 7  8]
 [11 12]]
r7 : [[ 6  7]
 [10 11]]
