<a href="https://colab.research.google.com/github/yym10618/Colab/blob/master/Ch01.%ED%8C%8C%EC%9D%B4%EC%8D%AC%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EB%B6%84%EC%84%9D%20%EA%B8%B0%EC%B4%88/Numpy_%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
"""
날짜 : 2022/04/28
이름 : 양용민
내용 : Numpy 연습문제
"""

#라이브러리 선언
import numpy as np

In [3]:
# 01. 파이썬 리스트 연산
list1 = [1, 2]
list2 = [3, 4]
print(list1 + list2)

[1, 2, 3, 4]


In [4]:
# 02. 넘파이 리스트(벡터) 연산
list1 - np.array([1,2])
list2 = np.array([3,4])
print(list1 + list2)

[4 6]


In [5]:
# 03. 0 벡터 생성 #1
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
# 04. 0 벡터 생성 #2
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
# 05. 10 ~ 49까지 벡터 생성
z = np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
# 06. 0부터 50까지 벡터 생성
z = np.arange(50)
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [10]:
# 07. index 1부터 index 10까지
z = np.arange(50)
z = z[1:10]
print(z)

[1 2 3 4 5 6 7 8 9]


In [12]:
# 08. index 1부터 index 10까지 2칸 간격으로
z = np.arange(50)
z = z[1:10:2]
print(z)

[1 3 5 7 9]


In [13]:
# 09. 처음부터 끝까지 2칸 간격으로
z = np.arange(50)
z = z[::2]
print(z)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


In [14]:
# 10. 10부터 끝까지
z = np.arange(50)
z = z[10::]
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [15]:
# 11. 1부터 끝까지 2칸 간격으로
z = np.arange(50)
z = z[1::2]
print(z)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [16]:
# 12. 처음부터 끝까지 -1칸 간격으로(==역순으로)
z = np.arange(50)
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [17]:
# 13. 3x3 벡터(행렬) 생성
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
# 14. 3x3 벡터(행렬) 인덱싱
z = np.arange(9).reshape(3,3)
z = z[1:3, 0:3]
print(z)

[[3 4 5]
 [6 7 8]]


In [20]:
# 15. 3x3 벡터(행렬) 인덱싱
z = np.arange(9).reshape(3,3)
z = z[:2,1:]
print(z)

[[1 2]
 [4 5]]


In [21]:
# 16. 3x3 벡터(행렬) 인덱싱
z = np.arange(9).reshape(3,3)
z = z[[0,1], 2]
print(z)

[2 5]


In [22]:
# 17. 3x3 벡터(행렬) 인덱싱
z = np.arange(9).reshape(3,3)
z = z[[0,1], 0:2]
print(z)

[[0 1]
 [3 4]]


In [23]:
# 18. 3x3 벡터(행렬) 인덱싱
z = np.arange(9).reshape(3,3)
z = z[[0, 1]]
print(z)

[[0 1 2]
 [3 4 5]]


In [24]:
# 19. 2x3 벡터(행렬) 생성
z = np.arange(6).reshape(2,3)
print(z)

[[0 1 2]
 [3 4 5]]


In [25]:
# 20. 2x5 벡터(행렬) 생성
z = np.arange(10).reshape(2,5)
print(z)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [26]:
# 21. 5x2 벡터(행렬) 생성
z = np.arange(10).reshape(5,2)
print(z)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [27]:
# 22. 자동x5 벡터(행렬) 생성
z = np.arange(10).reshape(-1,5)
print(z)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [28]:
# 23. 5x자동 벡터(행렬) 생성
z = np.arange(10).reshape(5,-1)
print(z)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [29]:
# 24. 0이 아닌 값들의 index 반환
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)

(array([0, 1, 4]),)


In [30]:
# 25. 2차 단위행렬
z = np.eye(2)
print(z)

[[1. 0.]
 [0. 1.]]


In [31]:
# 26. 3차 단위행렬
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
# 27. 3x3x3 벡터 생성
z = np.random.random((3,3,3))
print(z)

[[[0.49128721 0.69616977 0.84820989]
  [0.59310206 0.85341625 0.0807263 ]
  [0.47832625 0.9247561  0.18497128]]

 [[0.0132879  0.65180138 0.82550276]
  [0.03161481 0.59586735 0.81615071]
  [0.68518426 0.27150411 0.03352212]]

 [[0.22397971 0.33878813 0.40427646]
  [0.83006623 0.16397239 0.06958618]
  [0.00105012 0.20987049 0.19786957]]]


In [33]:
# 28. 10x10 벡터에서 최대, 최소값
z = np.random.random((10,10))
z_min, z_max = z.min(), z.max()
print('z_min :', z_min)
print('z_max :', z_max)

z_min : 0.025202007480497945
z_max : 0.9880728268281294


In [35]:
# 29. 벡터 평균
z = np.random.random(30)
m = z.mean()
print(z)
print(m)

[0.01603678 0.35201447 0.92253796 0.81787471 0.00892834 0.55168608
 0.31199007 0.23784047 0.83673125 0.66096429 0.55066016 0.98460344
 0.37500151 0.19253989 0.5720237  0.33117714 0.73829372 0.11709982
 0.08168998 0.98413779 0.86400996 0.6776453  0.3030756  0.85693488
 0.33274756 0.34069428 0.92191839 0.31342621 0.8422335  0.36703077]
0.5154516001348719


In [36]:
# 30. 10x10 벡터(행렬)에서 border가 1인 벡터
z = np.ones((10, 10))
z[1:-1, 1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [37]:
# 31. 10x10 벡터(행렬)에서 0, 1 체크무늬 벡터
z = np.zeros((10, 10))
z[1::2, ::2] = 1
z[::2, 1::2] = 1
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]]
